In [10]:
import numpy as np
import pickle
import os
from scipy.stats import entropy

In [11]:
# hypermaml
sq,uq,ss,us = None,None,None,None

with(open('exp_1_data/hyper_maml_fullSeenQuery_DATA','rb')) as fsq:
    sq=pickle.load(fsq)
with(open('exp_1_data/hyper_maml_fullUnseenQuery_DATA','rb')) as fuq:
    uq=pickle.load(fuq)
with(open('exp_1_data/hyper_maml_fullSeenSupport_DATA','rb')) as fss:
    ss=pickle.load(fss)
with(open('exp_1_data/hyper_maml_fullUnseenSupport_DATA','rb')) as fus:
    us=pickle.load(fus)

ss_mean = np.mean(ss,axis=0,dtype=np.float64)
us_mean = np.mean(us,axis=0,dtype=np.float64)
sq_mean = np.mean(sq,axis=0,dtype=np.float64)
uq_mean = np.mean(uq,axis=0,dtype=np.float64)

sq_entropy = entropy(sq_mean,axis=1,base=2)
uq_entropy = entropy(uq_mean,axis=1,base=2) # 80 punktow query
ss_entropy = entropy(ss_mean,axis=1,base=2) # 5 punktow supportu
us_entropy = entropy(us_mean,axis=1,base=2)

all_entropies = np.array([us_entropy,ss_entropy,uq_entropy,sq_entropy])
# tu masz entropie punktowo dla kazdego odpytujacego punktu
print(all_entropies)
with(open('./all_entropies_hypermaml','wb')) as f:
    pickle.dump(all_entropies,f)

[array([2.26809394, 2.25213875, 2.29048754, 2.29186378, 2.19330214])
 array([1.86506825, 1.9146496 , 2.06920583, 1.78142632, 2.06436925])
 array([2.30848492, 2.31376271, 2.29965449, 2.28752415, 2.3048478 ,
       2.30045454, 2.30850665, 2.3158761 , 2.30663352, 2.30088655,
       2.29462731, 2.28529253, 2.24885702, 2.24945789, 2.25760437,
       2.30085196, 2.281234  , 2.31723325, 2.26755396, 2.29946059,
       2.26676497, 2.27506364, 2.3002243 , 2.30714474, 2.26203719,
       2.24797334, 2.23512182, 2.25909173, 2.29104579, 2.3104209 ,
       2.28097074, 2.28720559, 2.30275093, 2.27216702, 2.27344522,
       2.28322387, 2.30005674, 2.30584528, 2.29927331, 2.28145142,
       2.30953462, 2.28792925, 2.27175469, 2.26333651, 2.29120992,
       2.26314305, 2.2805707 , 2.30300079, 2.28997331, 2.27367041,
       2.2618257 , 2.29214598, 2.28634964, 2.25110377, 2.31196065,
       2.29272962, 2.29572669, 2.27564798, 2.30359187, 2.30669555,
       2.2714948 , 2.24651399, 2.29050927, 2.2614357 , 2.

C:\Users\User\AppData\Local\Temp/ipykernel_29220/1284787240.py:23: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  all_entropies = np.array([us_entropy,ss_entropy,uq_entropy,sq_entropy])


In [12]:
# fhypermaml
sq,uq,ss,us = None,None,None,None

with(open('exp_1_data/fhyper_maml_fullSeenQuery_DATA','rb')) as fsq:
    sq=pickle.load(fsq)
with(open('exp_1_data/fhyper_maml_fullUnseenQuery_DATA','rb')) as fuq:
    uq=pickle.load(fuq)
with(open('exp_1_data/fhyper_maml_fullSeenSupport_DATA','rb')) as fss:
    ss=pickle.load(fss)
with(open('exp_1_data/fhyper_maml_fullUnseenSupport_DATA','rb')) as fus:
    us=pickle.load(fus)

ss_mean = np.mean(ss,axis=0,dtype=np.float64)
us_mean = np.mean(us,axis=0,dtype=np.float64)
sq_mean = np.mean(sq,axis=0,dtype=np.float64)
uq_mean = np.mean(uq,axis=0,dtype=np.float64)

sq_entropy = entropy(sq_mean,axis=1,base=2)
uq_entropy = entropy(uq_mean,axis=1,base=2) # 80 punktow query
ss_entropy = entropy(ss_mean,axis=1,base=2) # 5 punktow supportu
us_entropy = entropy(us_mean,axis=1,base=2)

all_entropies = np.array([us_entropy,ss_entropy,uq_entropy,sq_entropy])
# tu masz entropie punktowo dla kazdego odpytujacego punktu
print(all_entropies)
with(open('./all_entropies_fhypermaml','wb')) as f:
    pickle.dump(all_entropies,f)

[array([0.99148414, 1.5404266 , 0.07428566, 0.28375625, 0.98126091])
 array([3.59787496e-02, 2.69157182e-05, 9.88618092e-02, 1.33211688e-03,
       2.91350952e-03])
 array([2.31146330e-01, 5.99159150e-02, 8.18164956e-01, 7.94598185e-02,
       2.36009056e-01, 5.22434240e-03, 9.88669818e-01, 2.95623152e-01,
       1.87107180e-01, 2.02394355e-01, 3.69494376e-01, 6.08213472e-03,
       6.30814720e-01, 2.11022327e-01, 1.52679904e-01, 9.82078196e-01,
       1.12947936e+00, 7.48494375e-02, 2.78917109e-01, 7.15299077e-01,
       5.25856965e-01, 3.19728136e-01, 5.28608767e-02, 7.13620809e-02,
       4.09699597e-01, 5.05843436e-01, 7.61586465e-01, 4.02320216e-01,
       2.48957444e-01, 5.97139854e-01, 5.59603485e-01, 2.80802315e-01,
       8.91169960e-01, 8.73942244e-03, 9.44298221e-01, 3.61939605e-01,
       6.79308023e-02, 1.54010942e-01, 1.71573999e-01, 8.82421371e-01,
       2.19632906e-01, 4.77194036e-01, 4.52583855e-02, 1.74712578e-02,
       8.24519622e-03, 7.76257339e-02, 1.54793605e+00

C:\Users\User\AppData\Local\Temp/ipykernel_29220/1305343329.py:23: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  all_entropies = np.array([us_entropy,ss_entropy,uq_entropy,sq_entropy])


In [13]:
# bayes_hmaml

sq,uq,ss,us = None,None,None,None

with(open('exp_1_data/bayes_hmaml_fullSeenQuery_DATA','rb')) as fsq:
    sq=pickle.load(fsq)
with(open('exp_1_data/bayes_hmaml_fullUnseenQuery_DATA','rb')) as fuq:
    uq=pickle.load(fuq)
with(open('exp_1_data/bayes_hmaml_fullSeenSupport_DATA','rb')) as fss:
    ss=pickle.load(fss)
with(open('exp_1_data/bayes_hmaml_fullUnseenSupport_DATA','rb')) as fus:
    us=pickle.load(fus)

ss_mean = np.mean(ss,axis=0,dtype=np.float64)
us_mean = np.mean(us,axis=0,dtype=np.float64)
sq_mean = np.mean(sq,axis=0,dtype=np.float64)
uq_mean = np.mean(uq,axis=0,dtype=np.float64)

sq_entropy = entropy(sq_mean,axis=1,base=2)
uq_entropy = entropy(uq_mean,axis=1,base=2) # 80 punktow query
ss_entropy = entropy(ss_mean,axis=1,base=2) # 5 punktow supportu
us_entropy = entropy(us_mean,axis=1,base=2)

all_entropies = np.array([us_entropy,ss_entropy,uq_entropy,sq_entropy])
# tu masz entropie punktowo dla kazdego odpytujacego punktu
print(all_entropies)
with(open('./all_entropies_bayes_hmaml','wb')) as f:
    pickle.dump(all_entropies,f)

[array([2.27914702, 2.23692765, 2.22682829, 2.23827069, 2.27633055])
 array([1.92696539, 1.85561423, 2.02946491, 1.96576203, 2.05995339])
 array([2.28406277, 2.22115484, 2.27812775, 2.23499982, 2.24927743,
       2.20540932, 2.26065314, 2.27291899, 2.2245483 , 2.24359575,
       2.16096184, 2.19944198, 2.25162621, 2.24442504, 2.24147078,
       2.22493982, 2.20731335, 2.26785458, 2.25006454, 2.27617796,
       2.24242759, 2.26470245, 2.27974054, 2.27417865, 2.25710759,
       2.16603166, 2.15603671, 2.26623481, 2.26446676, 2.26498894,
       2.25630072, 2.2254466 , 2.28043499, 2.29066656, 2.2086804 ,
       2.26181984, 2.22442456, 2.27597122, 2.26540407, 2.27924192,
       2.29167116, 2.22063495, 2.28047601, 2.23229966, 2.24847728,
       2.2573082 , 2.28379492, 2.24157573, 2.27541838, 2.28572507,
       2.25367047, 2.29580092, 2.27351715, 2.26281562, 2.29225033,
       2.27991637, 2.25921614, 2.30375805, 2.29745853, 2.29983026,
       2.30079661, 2.25269318, 2.23724512, 2.2769337 , 2.

C:\Users\User\AppData\Local\Temp/ipykernel_29220/2152133110.py:24: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  all_entropies = np.array([us_entropy,ss_entropy,uq_entropy,sq_entropy])


In [14]:
with(open('./all_entropies_fhypermaml','rb')) as f:
    _us_entropy,_ss_entropy,_uq_entropy,_sq_entropy = pickle.load(f)


In [15]:
_ss_entropy

array([3.59787496e-02, 2.69157182e-05, 9.88618092e-02, 1.33211688e-03,
       2.91350952e-03])

In [16]:
_us_entropy

array([0.99148414, 1.5404266 , 0.07428566, 0.28375625, 0.98126091])

In [17]:
_sq_entropy

array([1.19998822e-03, 2.26473659e-02, 2.40862113e-02, 5.14118653e-02,
       1.76724473e-02, 6.06419318e-02, 5.14562597e-02, 1.87629551e-02,
       1.16750325e-02, 3.96845249e-01, 1.42445546e-01, 2.09307642e-03,
       2.09154467e-02, 1.50430499e-02, 3.40446843e-02, 2.32203297e-02,
       4.61635053e-04, 3.05036107e-04, 2.44463420e-04, 1.48628104e-04,
       4.61813927e-04, 9.72208975e-04, 5.58680939e-04, 9.53105652e-02,
       8.03592028e-03, 5.37614382e-03, 8.69445781e-05, 1.60226495e-04,
       1.40906450e-03, 7.57755759e-02, 1.09481051e-02, 1.51942107e-05,
       2.20874883e-02, 5.39601951e-01, 1.02948479e-01, 3.56065311e-01,
       9.99516469e-01, 9.49986271e-02, 9.86804439e-01, 4.63853084e-01,
       3.38987940e-03, 1.61397408e-02, 7.29563867e-03, 8.14346414e-02,
       1.98297246e-01, 8.55815951e-02, 1.72662532e-02, 3.08275930e-02,
       2.12736948e-02, 2.47314710e-05, 1.83223881e-02, 5.33302048e-04,
       6.70755865e-05, 2.65590511e-02, 6.09785572e-04, 1.17984637e-04,
      

In [18]:
_uq_entropy

array([2.31146330e-01, 5.99159150e-02, 8.18164956e-01, 7.94598185e-02,
       2.36009056e-01, 5.22434240e-03, 9.88669818e-01, 2.95623152e-01,
       1.87107180e-01, 2.02394355e-01, 3.69494376e-01, 6.08213472e-03,
       6.30814720e-01, 2.11022327e-01, 1.52679904e-01, 9.82078196e-01,
       1.12947936e+00, 7.48494375e-02, 2.78917109e-01, 7.15299077e-01,
       5.25856965e-01, 3.19728136e-01, 5.28608767e-02, 7.13620809e-02,
       4.09699597e-01, 5.05843436e-01, 7.61586465e-01, 4.02320216e-01,
       2.48957444e-01, 5.97139854e-01, 5.59603485e-01, 2.80802315e-01,
       8.91169960e-01, 8.73942244e-03, 9.44298221e-01, 3.61939605e-01,
       6.79308023e-02, 1.54010942e-01, 1.71573999e-01, 8.82421371e-01,
       2.19632906e-01, 4.77194036e-01, 4.52583855e-02, 1.74712578e-02,
       8.24519622e-03, 7.76257339e-02, 1.54793605e+00, 2.63092115e-02,
       2.13898871e-02, 4.85742878e-01, 6.43975804e-01, 1.42982403e+00,
       6.43871796e-02, 1.17937032e+00, 1.01981622e+00, 1.05900323e+00,
      